# Formula for a Homebrew tap (hammadsaedi/homebrew-tap).
#
#   brew install hammadsaedi/tap/helikopter
#
# Generated by packaging/bump.sh — do not edit by hand.
class Helikopter < Formula
  desc "Helicopter for your terminal that keeps your machine awake"
  homepage "https://github.com/hammadsaedi/helikopter"
  version "1.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.2/helikopter_1.1.2_darwin_arm64.tar.gz"
      sha256 "c7d70789df7dbece26cce5d035389005626d510156108dcb46907b0c35849fb1"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.2/helikopter_1.1.2_darwin_amd64.tar.gz"
      sha256 "afc9d983cb23ca68365d265f97726afcc713501d42e0471f3fdc5828f89bd1fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.2/helikopter_1.1.2_linux_arm64.tar.gz"
      sha256 "33d3f7b4480d726b0ec31c250431bacb4acc7781a7a2500bd985091cf4e80476"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.2/helikopter_1.1.2_linux_amd64.tar.gz"
      sha256 "9ce67b6ead0344e15f33212317a1cb36fdbc81e99e3d7d7eae98637ab0e9c441"
    end
  end

  def install
    bin.install "helikopter"
  end

  test do
    assert_match "helikopter", shell_output("#{bin}/helikopter --version")
    assert_match "crimson", shell_output("#{bin}/helikopter --list-themes")
    # Not a terminal under brew test, so this takes the idle path and exits.
    system bin/"helikopter", "--duration", "2s", "--silence", "--no-awake"
  end
end
