# Formula for a Homebrew tap (hammadsaedi/homebrew-tap).
#
#   brew install hammadsaedi/tap/helikopter
#
# Generated by packaging/bump.sh — do not edit by hand.
class Helikopter < Formula
  desc "Helicopter for your terminal that keeps your machine awake"
  homepage "https://github.com/hammadsaedi/helikopter"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.0/helikopter_1.1.0_darwin_arm64.tar.gz"
      sha256 "17621bafccfac9664a641afac2e0cc221e6e89e312f783072df474a84deca5d6"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.0/helikopter_1.1.0_darwin_amd64.tar.gz"
      sha256 "bcff225b261b22b4b835773d40454a2c4ad4f7a0ee3531416b87aee11befecef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.0/helikopter_1.1.0_linux_arm64.tar.gz"
      sha256 "1630171bad4e9d9a618921c79a0ddeb97f83dca48507cf3c99ecca7488d72814"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.0/helikopter_1.1.0_linux_amd64.tar.gz"
      sha256 "fcfac0653e4bbb7b0e764bd6798eadb6401270585b07f8a6918f061f00eb3d86"
    end
  end

  def install
    bin.install "helikopter"
  end

  test do
    assert_match "helikopter", shell_output("#{bin}/helikopter --version")
    assert_match "crimson", shell_output("#{bin}/helikopter --list-themes")
    # Not a terminal under brew test, so this takes the idle path and exits.
    system bin/"helikopter", "--duration", "2s", "--silence", "--no-awake"
  end
end
