# Formula for a Homebrew tap (hammadsaedi/homebrew-tap).
#
#   brew install hammadsaedi/tap/helikopter
#
# Generated by packaging/bump.sh — do not edit by hand.
class Helikopter < Formula
  desc "Helicopter for your terminal that keeps your machine awake"
  homepage "https://github.com/hammadsaedi/helikopter"
  version "1.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.1/helikopter_1.1.1_darwin_arm64.tar.gz"
      sha256 "9f38f45334ad6286353b029556d4b6f6bbeacf4c46a5a7070a67538a45ec992c"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.1/helikopter_1.1.1_darwin_amd64.tar.gz"
      sha256 "5606939ec6f7bfae842b93ccc06bcdafc4612a8a035010ea916e86581c8ef62a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.1/helikopter_1.1.1_linux_arm64.tar.gz"
      sha256 "383067a4c51149aad7a9d663132530328827d35a82011865b578e3a93373b887"
    end
    on_intel do
      url "https://github.com/hammadsaedi/helikopter/releases/download/v1.1.1/helikopter_1.1.1_linux_amd64.tar.gz"
      sha256 "017a197211b815089db0187712adf6cffb9dee3150629dec24d51b27625df292"
    end
  end

  def install
    bin.install "helikopter"
  end

  test do
    assert_match "helikopter", shell_output("#{bin}/helikopter --version")
    assert_match "crimson", shell_output("#{bin}/helikopter --list-themes")
    # Not a terminal under brew test, so this takes the idle path and exits.
    system bin/"helikopter", "--duration", "2s", "--silence", "--no-awake"
  end
end
