#!/bin/sh
# Regenerate the Homebrew formula, Scoop manifest and winget manifests for a
# published release.
#
#   packaging/bump.sh v1.0.1
#
# Every hash comes from that release's own checksums.txt, so the manifests can
# never disagree with what was actually shipped. The files are written out
# whole rather than patched in place: editing them by position is the kind of
# thing that breaks quietly and ships the wrong hash.

set -eu

REPO="hammadsaedi/helikopter"

tag="${1:-}"
[ -n "$tag" ] || { echo "usage: packaging/bump.sh <tag>   e.g. v1.0.1" >&2; exit 1; }
ver="${tag#v}"

unset CDPATH
root=$(cd -- "$(dirname -- "$0")/.." && pwd)
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/checksums.txt") || {
  echo "error: no checksums.txt for $tag — is the release published?" >&2
  exit 1
}

hash() {
  h=$(printf '%s\n' "$sums" | awk -v f="helikopter_${ver}_$1" '$2 == f { print $1 }')
  [ -n "$h" ] || { echo "error: no checksum for helikopter_${ver}_$1" >&2; exit 1; }
  printf '%s' "$h"
}
upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

DARWIN_ARM=$(hash darwin_arm64.tar.gz)
DARWIN_X64=$(hash darwin_amd64.tar.gz)
LINUX_ARM=$(hash linux_arm64.tar.gz)
LINUX_X64=$(hash linux_amd64.tar.gz)
WIN_X64=$(hash windows_amd64.zip)
WIN_ARM=$(hash windows_arm64.zip)
WIN_X86=$(hash windows_386.zip)

echo "  generating packaging for $tag"

# --- Homebrew -------------------------------------------------------------
cat > "$root/packaging/homebrew/helikopter.rb" <<EOF
# Formula for a Homebrew tap (hammadsaedi/homebrew-tap).
#
#   brew install hammadsaedi/tap/helikopter
#
# Generated by packaging/bump.sh — do not edit by hand.
class Helikopter < Formula
  desc "Helicopter for your terminal that keeps your machine awake"
  homepage "https://github.com/$REPO"
  version "$ver"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/helikopter_${ver}_darwin_arm64.tar.gz"
      sha256 "$DARWIN_ARM"
    end
    on_intel do
      url "$base/helikopter_${ver}_darwin_amd64.tar.gz"
      sha256 "$DARWIN_X64"
    end
  end

  on_linux do
    on_arm do
      url "$base/helikopter_${ver}_linux_arm64.tar.gz"
      sha256 "$LINUX_ARM"
    end
    on_intel do
      url "$base/helikopter_${ver}_linux_amd64.tar.gz"
      sha256 "$LINUX_X64"
    end
  end

  def install
    bin.install "helikopter"
  end

  test do
    assert_match "helikopter", shell_output("#{bin}/helikopter --version")
    assert_match "crimson", shell_output("#{bin}/helikopter --list-themes")
    # Not a terminal under brew test, so this takes the idle path and exits.
    system bin/"helikopter", "--duration", "2s", "--silence", "--no-awake"
  end
end
EOF

# --- Scoop ----------------------------------------------------------------
cat > "$root/packaging/scoop/helikopter.json" <<EOF
{
    "version": "$ver",
    "description": "A helicopter flies in your terminal, and keeps your machine awake while it does.",
    "homepage": "https://github.com/$REPO",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "$base/helikopter_${ver}_windows_amd64.zip",
            "hash": "$WIN_X64"
        },
        "arm64": {
            "url": "$base/helikopter_${ver}_windows_arm64.zip",
            "hash": "$WIN_ARM"
        },
        "32bit": {
            "url": "$base/helikopter_${ver}_windows_386.zip",
            "hash": "$WIN_X86"
        }
    },
    "bin": "helikopter.exe",
    "notes": [
        "helikopter.exe is not code-signed. Windows Smart App Control blocks",
        "unsigned executables however they were installed, so it may still",
        "object on Windows 11. Allow it once in Windows Security, or build from",
        "source: go install github.com/$REPO/cmd/helikopter@latest"
    ],
    "checkver": {
        "github": "https://github.com/$REPO"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/$REPO/releases/download/v\$version/helikopter_\$version_windows_amd64.zip"
            },
            "arm64": {
                "url": "https://github.com/$REPO/releases/download/v\$version/helikopter_\$version_windows_arm64.zip"
            },
            "32bit": {
                "url": "https://github.com/$REPO/releases/download/v\$version/helikopter_\$version_windows_386.zip"
            }
        },
        "hash": {
            "url": "https://github.com/$REPO/releases/download/v\$version/checksums.txt"
        }
    }
}
EOF

# --- winget ---------------------------------------------------------------
wdir="$root/packaging/winget/manifests/h/hammadsaedi/helikopter/$ver"
mkdir -p "$wdir"

cat > "$wdir/hammadsaedi.helikopter.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: hammadsaedi.helikopter
PackageVersion: $ver
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$wdir/hammadsaedi.helikopter.installer.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: hammadsaedi.helikopter
PackageVersion: $ver
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: uninstallPrevious
Installers:
  - Architecture: x64
    InstallerUrl: $base/helikopter_${ver}_windows_amd64.zip
    InstallerSha256: $(upper "$WIN_X64")
    NestedInstallerFiles:
      - RelativeFilePath: helikopter.exe
        PortableCommandAlias: helikopter
  - Architecture: arm64
    InstallerUrl: $base/helikopter_${ver}_windows_arm64.zip
    InstallerSha256: $(upper "$WIN_ARM")
    NestedInstallerFiles:
      - RelativeFilePath: helikopter.exe
        PortableCommandAlias: helikopter
  - Architecture: x86
    InstallerUrl: $base/helikopter_${ver}_windows_386.zip
    InstallerSha256: $(upper "$WIN_X86")
    NestedInstallerFiles:
      - RelativeFilePath: helikopter.exe
        PortableCommandAlias: helikopter
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$wdir/hammadsaedi.helikopter.locale.en-US.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: hammadsaedi.helikopter
PackageVersion: $ver
PackageLocale: en-US
Publisher: Hammad Saeedi
PublisherUrl: https://github.com/hammadsaedi
PublisherSupportUrl: https://github.com/$REPO/issues
Author: Hammad Saeedi
PackageName: helikopter
PackageUrl: https://github.com/$REPO
License: MIT
LicenseUrl: https://github.com/$REPO/blob/main/LICENSE
ShortDescription: A helicopter flies in your terminal, and keeps your machine awake while it does.
Description: |-
  helikopter draws a shaded, animated helicopter in your terminal and holds an
  operating-system wake lock for as long as it runs, so the display and the
  machine stay awake.

  The airframe is a parametric model rasterised to whatever size the terminal
  is, so it stays sharp from 80x24 to full screen. Eight themes colour the whole
  scene. Without Unicode or colour it falls back to line art rather than a
  degraded copy of the colour render.

  Idle and paused cost no measurable CPU, so it can be left running.
Moniker: helikopter
Tags:
  - cli
  - terminal
  - animation
  - ascii-art
  - keep-awake
  - screensaver
ReleaseNotesUrl: https://github.com/$REPO/releases/tag/$tag
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

echo "  wrote homebrew, scoop and winget manifests for $ver"
echo "  review with: git diff packaging/"
